ratebeer/config/routes.rb
Rails.application.routes.draw do
  resources :beers
  resources :breweries

end

ratebeer/app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  has_many :ratings

  def average_rating
    
    d=self.ratings.average(:score)
    d
  end

  def to_s
    "#{self.name} #{self.brewery.name}"
  end
end

ratebeer/app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :beers 

  def print_report
    puts self.name
    puts "established at year #{self.year}"
    puts "number of beers #{self.beers.count}"
  end

  
end

ratebeer/app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :beer

  def to_s
    "#{self.beer.name} #{self.score}"
  end 
end

ratebeer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ratebeer/app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :style, :brewery_id)
    end
end

ratebeer/app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
	
    
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year)
    end
end

ratebeer/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
	@ratings = Rating.all
  end
  
  def new
    @rating = Rating.new
  end	
  def create
    Rating.create params.require(:rating).permit(:score, :beer_id)
    redirect_to ratings_path
  end
end

ratebeer/app/helpers/application_helper.rb
module ApplicationHelper
end

ratebeer/app/helpers/beers_helper.rb
module BeersHelper
end

ratebeer/app/helpers/breweries_helper.rb
module BreweriesHelper
end

ratebeer/app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :brewery_id %><br>
    <%= f.number_field :brewery_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ratebeer/app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

ratebeer/app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beers</h1>
  <tbody>
    <% @beers.each do |beer| %>
      <% byebug if beer.brewery.nil? %>
      <tr>
        
      </tr>
    <% end %>
  </tbody>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Style</th>
      <th>Brewery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= link_to beer.to_s, beer %></td>
        <td><%= beer.style %></td>
        <td><%= link_to beer.brewery.name, beer.brewery %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>
<br>
<%= link_to 'list of breweries', breweries_path %>

ratebeer/app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

ratebeer/app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Style:</strong>
  <%= @beer.style %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @beer.brewery_id %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

ratebeer/app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ratebeer/app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

ratebeer/app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breweries</h1>
<p> Number of breweries: <%= @breweries.count %> </p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name %></td>
        <td><%= brewery.year %></td>
        <td><%= link_to 'Show', brewery %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brewery', new_brewery_path %>
<br>
<%= link_to 'List of beers', beers_path %>
</br>

ratebeer/app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

ratebeer/app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @brewery.name %></h2>
  
</p>

<p>
  <i>Established in <%= @brewery.year %></i>
</p>
<p>
  Number of beers <%=@brewery.beers.count %>	
</p>
<p>
 <%@brewery.beers.each do |beer| %>
   <%=link_to beer.name %>
 <% end %>
</p>
<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>

ratebeer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratebeer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ratebeer/app/views/ratings/index.html.erb
<h2>List of ratings</h2>
<p> Number of ratings:  <%= @ratings.count %> </p>
<ul>
 <% @ratings.each do |rating| %>
   <li> <%= rating %> </li>
 <% end %>
<br>
<%= link_to 'New Rating', ratings_new_path %>

ratebeer/app/views/ratings/new.html.erb
<h2>Create new rating</h2>

<%= form_for(@rating) do |f| %>
  beer id: <%= f.number_field :beer_id %>
  score: <%= f.number_field :score %>
  <%= f.submit %>
<% end %>